export const WILL_FETCH_DEVICES ='WILL_FETCH_DEVICES';
export const  DID_FETCH_DEVICES_FOR_FLEET = 'DID_FETCH_DEVICES_FOR_FLEET';
export const DID_NOT_FETCH_DEVICES_FOR_FLEET = 'DID_NOT_FETCH_DEVICES_FOR_FLEET';
